using ProjectStockManagement.PaperStockManagementDB;
using System;
using System.Windows.Forms;
using System.Data.Entity;

namespace ProjectStockManagement
{
    /// <summary>
    /// Contain necessary action for adding Vehicle info.
    /// </summary>
    public partial class AddVehicle : Form
    {
        PaperStockManagementDBEntities paperStockManagementDB;
        /// <summary>
        /// Initialize insatance(constructor) of AddVehicle.
        /// </summary>
        public AddVehicle()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            paperStockManagementDB = new PaperStockManagementDBEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            paperStockManagementDB.Vehicles.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                grdCtrlAddVehicle.DataSource = paperStockManagementDB.Vehicles.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        /// <summary>
        /// Occurs when ADD VEHICLE button will be pressed.
        /// </summary>
        /// <param name="sender">Insatance of Object.</param>
        /// <param name="e">Instance of EventArgs.</param>
        private void btnAddVehicle_Click(object sender, EventArgs e)
        {
            // Add new Vehicle details to data-base.
            using (paperStockManagementDB)
            {
                var vehicle = new Vehicle();
                vehicle.Number = txtAddVehicle.Text;
                paperStockManagementDB.Vehicles.Add(vehicle);
                paperStockManagementDB.SaveChanges();
                PaperStockManagement.VehicleList.Add(vehicle.Number);
            }

            this.Close();
        }

        /// <summary>
        /// Close the form.
        /// </summary>
        /// <param name="sender">Insatance of Object.</param>
        /// <param name="e">Insatance of EventArgs.</param>
        private void btnCancleVehicle_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        /// <summary>
        /// Ocuurs when any key will press.
        /// </summary>
        /// <param name="sender">Instance of Object.</param>
        /// <param name="e">Instance of KeyPressEventArgs.</param>
        private void AddVehicle_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (e.KeyChar == (char)Keys.Escape)
            {
                this.Close();
            }
        }

        private void grdViewAddVehicle_RowDeleted(object sender, DevExpress.Data.RowDeletedEventArgs e)
        {
            paperStockManagementDB.SaveChanges();
        }

        private void grdViewAddVehicle_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            paperStockManagementDB.SaveChanges();
        }
    }
}
