using System;
using System.Windows.Forms;
using System.Data.Entity;
using ProjectStockManagement.PaperStockManagementDB;

namespace ProjectStockManagement
{
    public partial class DeleteOrder : Form
    {
        PaperStockManagementDBEntities paperStockManagementDB;

        public DeleteOrder()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            paperStockManagementDB = new PaperStockManagementDBEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            paperStockManagementDB.Orders.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                grdCtrlDeleteOrder.DataSource = paperStockManagementDB.Orders.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
