//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStockManagement.PaperStockManagementDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int StockID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Deleted { get; set; }
        public Nullable<long> VehicleID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
