//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStockManagement.PaperStockManagementDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaperStockManagementDBEntities : DbContext
    {
        public PaperStockManagementDBEntities()
            : base("name=PaperStockManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddOrder> AddOrders { get; set; }
        public virtual DbSet<AuthenticationUser> AuthenticationUsers { get; set; }
        public virtual DbSet<BreakingForce> BreakingForces { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DispatchOrder> DispatchOrders { get; set; }
        public virtual DbSet<GSM> GSMs { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
    }
}
