//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStockManagement.PaperStockManagementDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.Orders = new HashSet<Order>();
            this.StockInventories = new HashSet<StockInventory>();
        }
    
        public int ID { get; set; }
        public int GSM { get; set; }
        public int BreakingForce { get; set; }
        public double Size { get; set; }
        public double Weight { get; set; }
    
        public virtual BreakingForce BreakingForce1 { get; set; }
        public virtual GSM GSM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockInventory> StockInventories { get; set; }
    }
}
